name: Sync Booqable to Reeleezee

on:
  # schedule:
  #   - cron: '30 21 * * *'  # Run daily at 11:30 PM Amsterdam time (9:30 PM UTC)
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync script
        env:
          BOOQABLE_API_KEY: ${{ secrets.BOOQABLE_API_KEY }}
          REELEEZEE_USERNAME: ${{ secrets.REELEEZEE_USERNAME }}
          REELEEZEE_PASSWORD: ${{ secrets.REELEEZEE_PASSWORD }}
        run: python main.py